### ISSUE TITLE
[Bug?] `Modrinth project "ID" was not found` when publish to project under review

### ISSUE THREAD

**Issue by SettingDust** [Kir-Antipov/mc-publish#101]
https://github.com/SettingDust/HeraclesForVillagers/actions/runs/7406044254/job/20149871838

https://discord.com/channels/734077874708938864/1192699041402855544/1192714099931480074

> The problem is because Kir-Antipov/mc-publish is not made by us, it does some extra checks that are unnecessary, which gives this error

Seems this project is checking the project info.

**Comment by Kir-Antipov** [comment]
I cannot open the Discord discussion you've attached *(Discord nuked my 6-year-old account with all its data, so I don't really want to touch that platform ever again)*, but I assume that the token you provided to `mc-publish` has no `Read projects` permission. It's not required most of the time, but when you are dealing with a private project *(e.g., one that hasn't been reviewed yet, like in your case)*, without it, Modrinth will make it seem like it doesn't exist at all.

You can see the full list of permissions `mc-publish` may require [here](https://github.com/Kir-Antipov/mc-publish/discussions/88#discussioncomment-7153913). I know that this information should be in a more accessible place than an obscure GitHub discussion, but I haven't had time to finish a wiki yet. It will be completed for `mc-publish@v4`, though.

So, is it a bug? No, it's pretty much an expected behavior. Can I add a workaround for cases when the permission is missing? Yep, I will do that in a moment.

---

Also, as a side note, don't bother people from Modrinth if you have problems with or questions about `mc-publish`. The folks are already doing God's work; no need to burden them with other projects that hardly have anything to do with theirs. So, go straight to this repo. I may be slow to respond sometimes, but still :)
