### ISSUE TITLE
Not finding Modrinth id

### ISSUE THREAD

**Issue by fxmorin** [Kir-Antipov/mc-publish#11]
https://github.com/fxmorin/MoreCulling/runs/6887202208?check_suite_focus=true

Modrinth id is located [here](https://github.com/fxmorin/MoreCulling/blob/master/src/main/resources/fabric.mod.json#L35)

**Comment by Kir-Antipov** [comment]
Not really. `mc-publish` does not scan your entire repository in order to find the required metadata. It takes it directly from the primary file specified by you. Your primary file is `moreculling-1.19-0.3.0-alpha-api.jar`, and it doesn't contain `fabric.mod.json`. Either change globs for the `files-primary` and `files-secondary` fields to something like `build/libs/!(*-@(dev|sources|api)).jar` and `build/libs/*-@(dev|sources|api).jar`, or add `fabric.mod.json` to the file that is considered a primary one

**Comment by Kir-Antipov** [comment]
Btw, cool mod you have there :)
