### ISSUE TITLE
Description sync

### ISSUE THREAD

**Issue by OffsetMonkey538** [Kir-Antipov/mc-publish#19]
Would it be possible add a ``description-file`` or ``readme-file`` option?
I'd like to just update the readme in the repo and when releasing the mod, it would automagically set the description on Modrinth and/or CurseForge.
Not sure if it's possible with Curse but I do know it should be possible with Modrinth.

**Comment by Kir-Antipov** [comment]
I thought about that, because it annoys me to update CurseForge's description and Modrinth's readme manually every time. Unfortunately, there are several factors that hold me back:

1) CurseForge does not have a public API that would allow users to update their project's description
2) CurseForge's markdown sucks, therefore we need some kind of "transformer" that will convert a markdown file to a much more primitive form, so it won't be **that** broken when uploaded 
3) Modrinth's markdown is nice, but it has its own differences from GitHub Flavored Markdown™, so we still need something that is able to tweak a markdown file

While points 2 and 3 make it significantly harder to implement, because they require a lot of new concepts to be presented, which will make mc-publish exponentially more difficult for a user to comprehend, point 1 makes it *almost* impossible to do, because the project targets a high abstraction level *(i.e., we can do something for either all targets or none of them)*

All that said, I still want to implement something like this, but if I do, it will definitely be a different project.

**Comment by OffsetMonkey538** [comment]
Thanks for the reply!
I mainly just use Modrinth so I'll just add a custom thing after mc-publish that syncs the readme to modrinth
