### ISSUE TITLE
ResourcePack upload

### ISSUE THREAD

**Issue by xMikux** [Kir-Antipov/mc-publish#21]
Hi, I am trying to setup with this action to my workflows, but when I publish, the action fail with ``Error: At least one mod loader should be specified``

I didn't see any option for resourcepack.

**Comment by Kir-Antipov** [comment]
You need to specify at least one loader, because this is a requirement of the target platforms you upload your files to *(i.e., Modrinth anc CurseForge)*. 

Based on the response of the ["tag/loader"](https://api.modrinth.com/v2/tag/loader) endpoint, I can infer that Modrinth uses `minecraft` as a loader type for resource packs:
```json
{
  "icon": "...",
  "name": "minecraft",
  "supported_project_types": ["resourcepack"]
}
```

Therefore, you should be fine if you add this line to your configuration:
```yaml
  loaders: minecraft
```

Let me know how it goes :)

**Comment by xMikux** [comment]
Yeah, it work now, thanks for your help!

**Comment by xMikux** [comment]
It Will be great to have some info on ``README.md`` file!

**Comment by Kir-Antipov** [comment]
I'll add it after I implement built-in support for resource packs :)
