### ISSUE TITLE
Make `modrinth-featured` false by default

### ISSUE THREAD

**Issue by Andre601** [Kir-Antipov/mc-publish#24]
There isn't really a use in having `modrinth-featured` set to true by default.
The Modrinth site will automatically feature a version for a specific (set of) version(s).

Like, when I publish version 1.1 of my resource for MC version 1.19.2 and there is already a resource listed for that version (which isn't featured by yourself) will modrinth replace the featured resource with the new one.

This option only makes sense for people that only want one specific version to be featured while not displaying those of other MC versions and even then is the default resolving of features actually respecting different versions... or something like that.

Either way, this option doesn't quite make sense to be true by default as the normal use-case would already work fine with Modrinth's auto-feature behaviour.

**Comment by Kir-Antipov** [comment]
> There isn't really a use in having `modrinth-featured` set to true by default.

I'm gonna stop you right there. That's why it's possible to configure the action in the first place - everybody has their own needs and views on their perfect publishing process. The purpose of a default value is to represent something that makes the most sense and is therefore suitable for most users.

In this particular case the logic is quite simple - if I publish a file I **always** want others to be able to see it, so `modrinth-featured: true` makes the most sense in this scenario. Let's take a look at preferences of users of this project. Currently, there are 162 public repositories that use mc-publish and are indexed by GitHub. I've quickly [processed all of them](https://gist.github.com/Kir-Antipov/f831f48c5d0867d94e0345e6cce2e63b), and I can tell you that

 - **134** of them use mc-publish to publish their assets to Modrinth
 - **131** users (or `97.76%`) prefer **modrinth-featured** to be set to `true`. In order to be a little more specific, 85% do not specify value at all and rely on the existing default value, and 12.7% provide true explicitly
 - And only **3** people (or `2.24%`) do not think that there is a use in having **modrinth-featured** set to true, with you being one of them, or 33.(3)% of those 2.24% :)

So, no, I won't change the behavior my users rely on since when `modrinth-featured` was not even an option, breaking 85% of existing configurations.
