### ISSUE TITLE
Depreciation warnings when using action

### ISSUE THREAD

**Issue by ApexModder** [Kir-Antipov/mc-publish#39]
The following warning about depreciation is given when using this action.
Solutions are provided via the warnings links

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Kir-Antipov/mc-publish

The solution from given link
> For Actions maintainers: Update your actions to run on Node 16 instead of Node 12 ([Actions configuration settings](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions))

**Comment by Kir-Antipov** [comment]
Oh no. I have a stale branch that targets Node 16, but there are a lot of problems with dependencies there

**Comment by Kir-Antipov** [comment]
In order to follow this up, I'm working on updating the action to Node16 (alongside with lots of new features) locally. Also, there's plenty of time to get things done until Summer 2023 *(GitHub will discontinue support of Node12 actions somewhere around that time)*, so don't worry.

Node12 may be deprecated, but mc-publish itself won't be until there's at least one fellow developer that needs it :)

**Comment by cech12** [comment]
There are only about 2 months left until summer 2023. Are there any news for this issue? :)

**Comment by Kir-Antipov** [comment]
Yup, will be there on time. Don't worry! The project went through almost a complete rewrite, so it took some time

**Comment by osfanbuff63** [comment]
On May 18, actions on Node 12 will run Node 16 instead. ([source](https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12)). Seems a little early for "Summer 2023"...

**Comment by Kir-Antipov** [comment]
Thanks a million for alerting me about GitHub Actions moving to Node 16 on May 18th, earlier than the previously announced "Summer 2023". I appreciate the info, as I was still planning based on the original timeline.

Given this change, I'll adjust my plans accordingly. Instead of releasing v4.0, I'll work on a v3.3 release, which won't include support for new platforms and project types but will run on Node 16, allowing users to continue using it without issues. This release will also serve as a starting point for deprecating certain parts of the project I'm not entirely satisfied with.

By introducing the deprecation process in v3.3, users will have ample time to migrate their configurations to the new format. This way, when v4.0 is eventually released, we can move forward without any legacy baggage.

Thanks again for bringing this to my attention!

**Comment by Kir-Antipov** [comment]
[v3.3](https://github.com/Kir-Antipov/mc-publish/releases/tag/v3.3) is now available!
