### ISSUE TITLE
GitHub token requires read/write permissions

### ISSUE THREAD

**Issue by MattiDragon** [Kir-Antipov/mc-publish#55]
My publish workflow has failed to publish to git twice now: 
 - https://github.com/MattiDragon/PowerNetworks/actions/runs/4525233020
 - https://github.com/MattiDragon/PowerNetworks/actions/runs/4589978543

I have manually published the releases, so that's why you see them. 
I have no idea why it's broken, but it is

**Comment by Kir-Antipov** [comment]
I'm pretty sure you were using a nonexistent tag name, that's why the action has failed.

**Comment by NebelNidas** [comment]
Ah, sorry. I've searched through GitHub's changelog a bit, and it seems like [this change](https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/) is the cause

**Comment by Kir-Antipov** [comment]
Oh, that makes a lot of sense now! Thank you. Also, I see now why I didn't notice it earlier - it's been a while since I created new repositories, and the old ones still have read/write permissions by default.

@MattiDragon, so, all you need to do is got to your repository's settings, `Actions -> General -> Workflow permissions`, and choose `Read and write permissions` there:

![Permissions](https://user-images.githubusercontent.com/40232067/234666530-35d7293c-0d4d-4e2c-89e0-50985614623c.png)

Let me know if the problem persists!

**Comment by Fallen-Breath** [comment]
Another workaround for this is to manually specify the permission grant for the `GITHUB_TOKEN`, e.g.

```yml
jobs:
  my_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # <- add this
    steps:
      # ...
```

This allow the workflow to modify github releases

See:
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
- https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents
