### ISSUE TITLE
HttpError 400  when publishing to modrinth: Field game_versions failed validation with error: length

### ISSUE THREAD

**Issue by mineblock11** [Kir-Antipov/mc-publish#70]
https://github.com/mineblock11/SimpleBroadcast/actions/runs/5148324340 (>=1.20 <1.21)

However, works fine here? https://github.com/mineblock11/MRU/actions/runs/5147207350 (>=1.20 <1.21)

```log
Run Kir-Antipov/mc-publish@v3.3
  with:
    modrinth-id: ijqqUY8R
    modrinth-token: ***
    curseforge-id: 859606
    curseforge-token: ***
    github-token: ***
    modrinth-featured: ${undefined}
    modrinth-unfeature-mode: subset
    github-tag: ${undefined}
    github-generate-changelog: ${undefined}
    github-draft: ${undefined}
    github-prerelease: ${undefined}
    github-commitish: ${undefined}
    github-discussion: ${undefined}
    files: build/libs/!(*-@(dev|sources|javadoc)).jar
  build/libs/*-@(dev|sources|javadoc).jar
  
    files-primary: ${undefined}
    files-secondary: ${undefined}
    name: ${undefined}
    version: ${undefined}
    version-type: ${undefined}
    changelog: ${undefined}
    changelog-file: ${undefined}
    loaders: ${undefined}
    game-versions: ${undefined}
    dependencies: ${undefined}
    version-resolver: ${undefined}
    game-version-filter: releases | min-major | min-minor
    java: ${undefined}
    retry-attempts: [2](https://github.com/mineblock11/SimpleBroadcast/actions/runs/5148324340/jobs/9269856587#step:8:2)
    retry-delay: 10000
    fail-mode: fail
    modrinth-files: ${undefined}
    curseforge-files: ${undefined}
    github-files: ${undefined}
    modrinth-files-primary: ${undefined}
    curseforge-files-primary: ${undefined}
    github-files-primary: ${undefined}
    modrinth-files-secondary: ${undefined}
    curseforge-files-secondary: ${undefined}
    github-files-secondary: ${undefined}
    modrinth-name: ${undefined}
    curseforge-name: ${undefined}
    github-name: ${undefined}
    modrinth-version: ${undefined}
    curseforge-version: ${undefined}
    github-version: ${undefined}
    modrinth-version-type: ${undefined}
    curseforge-version-type: ${undefined}
    github-version-type: ${undefined}
    modrinth-changelog: ${undefined}
    curseforge-changelog: ${undefined}
    github-changelog: ${undefined}
    modrinth-changelog-file: ${undefined}
    curseforge-changelog-file: ${undefined}
    github-changelog-file: ${undefined}
    modrinth-loaders: ${undefined}
    curseforge-loaders: ${undefined}
    github-loaders: ${undefined}
    modrinth-game-versions: ${undefined}
    curseforge-game-versions: ${undefined}
    github-game-versions: ${undefined}
    modrinth-dependencies: ${undefined}
    curseforge-dependencies: ${undefined}
    github-dependencies: ${undefined}
    modrinth-version-resolver: ${undefined}
    curseforge-version-resolver: ${undefined}
    github-version-resolver: ${undefined}
    modrinth-game-version-filter: ${undefined}
    curseforge-game-version-filter: ${undefined}
    github-game-version-filter: ${undefined}
    modrinth-java: ${undefined}
    curseforge-java: ${undefined}
    github-java: ${undefined}
    modrinth-retry-attempts: ${undefined}
    curseforge-retry-attempts: ${undefined}
    github-retry-attempts: ${undefined}
    modrinth-retry-delay: ${undefined}
    curseforge-retry-delay: ${undefined}
    github-retry-delay: ${undefined}
    modrinth-fail-mode: ${undefined}
    curseforge-fail-mode: ${undefined}
    github-fail-mode: ${undefined}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64
  
📤 Uploading assets to CurseForge
✅ Successfully published assets to CurseForge in 1[3](https://github.com/mineblock11/SimpleBroadcast/actions/runs/5148324340/jobs/9269856587#step:8:3)7[4](https://github.com/mineblock11/SimpleBroadcast/actions/runs/5148324340/jobs/9269856587#step:8:4) ms
📤 Uploading assets to Modrinth
Error: HttpError: [40](https://github.com/mineblock11/SimpleBroadcast/actions/runs/5148324340/jobs/9269856587#step:8:40)0 (Bad Request, {"error":"invalid_input","description":"Error while validating input: Field game_versions failed validation with error: length"})
```

**Comment by Kir-Antipov** [comment]
The second one uses outdated `v3.2`. In `v3.3` I added logic that sorts versions unknown by Modrinth out. It seems, in your case everything was sorted out. Let me investigate it a little bit further.

**Comment by Kir-Antipov** [comment]
Oh, wait. `v3.3` works as expected. There's no `1.20` yet! What are you trying to do?

**Comment by Kir-Antipov** [comment]
But the one thing that really needs my attention, which I can see here, is that I do need to throw validation errors on my end, before a faulty request is ever sent to Modrinth/CurseForge/etc. Sadly, these things were lost during `v3.3` rewrite.

**Comment by mineblock11** [comment]
>Oh, wait. v3.3 works as expected. There's no 1.20 yet! What are you trying to do?

\>=1.20 should satisfy all snapshots, pre-releases and release candidates.

**Comment by mineblock11** [comment]
This is the case for fabric

**Comment by Kir-Antipov** [comment]
> \>=1.20 should satisfy all snapshots, pre-releases and release candidates.

No, the range `>=1.20` wouldn't include all those versions. According to Semantic Versioning rules, `1.20` is considered a release that is subsequent to its preceding snapshots, making them excluded from the `>=1.20` range.

To my knowledge, the Fabric Loader follows these standard guidelines as well, but it's difficult to assert this conclusively since their documentation doesn't specify how they interpret ranges. Hence, even if Fabric applies more lenient rules when evaluating the range, it's merely an implementation detail that I wouldn't advise relying on.

The SemVer range `>=1.20` effectively translates to "1.20 and all subsequent versions". Snapshots of version 1.20 don't qualify as any of these things. Thus, including them would not only contradict the generally accepted SemVer range semantics but could also lead to confusion among end users, making it an undesirable outcome.

Alternatively, you could strictly adhere to the semantics and use either `>1.19.4 <1.21` or `>=1.20-alpha.23.12.a`. You could also use `>=23w12a <1.21` with `mc-publish`, although I'm unsure whether Fabric supports this type of range. These options are descriptive, transparently conveying your intentions. They comply with the specifications, don't depend on third-party implementation nuances, and are recognized by Fabric. What more could one ask for?

**Comment by Kir-Antipov** [comment]
Moreover, even if the range was correctly specified, the action would still fail due to your current configuration. Your `game-version-filter` is set to `releases | min-major | min-minor`, thereby excluding non-release versions. This means everything in your case would ultimately be filtered out anyway. Consider using `min-major | min-minor` or `none` filter instead.

**Comment by Kir-Antipov** [comment]
[`@modmuss`](https://discord.com/channels/507304429255393322/566276937035546624/1113936758304952371):

> [...]. `>=1.20` would be the stable 1.20 and any future snapshots/versions.

So, yeah. As I said, Fabric follows the rules everybody follows.

**Comment by Kir-Antipov** [comment]
Okie-dokie :D

Also, as a fellow developer that actually tinkers with snapshots, do you think that I need to re-introduce `version-resolver: releasesIfAny` logic in new `game-version-filter`? How often do you publish snapshot-exclusive versions? And would you want your configuration to remain unchanged for those scenarios?

**Comment by mineblock11** [comment]
> do you think that I need to re-introduce version-resolver: releasesIfAny logic in new game-version-filter?
Probably not! It's a super edge case.

> How often do you publish snapshot-exclusive versions?
Only really when the release candidates come out (since they're usually the exact same as the release version)
