### ISSUE TITLE
Fail to upload - version 3.3

### ISSUE THREAD

**Issue by MrNavaStar** [Kir-Antipov/mc-publish#71]
Not sure whats causing this issue or how to fix it. Can't seem to find anything about it in the documentation:
![image](https://github.com/Kir-Antipov/mc-publish/assets/43613843/c6cd4750-57aa-475e-9b78-2eaeeb228c62)

Here is my workflow, the mc-publish bit is right at the bottom:
https://github.com/MrNavaStar/SQLib/blob/master/.github/workflows/publish.yml

I am using a fabric.mod.json to get the metadata into mc-publish:
![image](https://github.com/Kir-Antipov/mc-publish/assets/43613843/2f748150-f8fa-4026-937d-686601fb39dc)

Cheers!

**Comment by Kir-Antipov** [comment]
I apologize as there seems to be a bit of a regression with my error messages; some of them are not very user-friendly at the moment.

The error you're encountering could be translated into more understandable terms as follows:

> The glob `/home/runner/work/SQLib/SQLib/sqlib-2.1.4.jar` has not matched any files.

To troubleshoot, let's deconstruct your configuration:

1) You're building your mod. The output file is named `/home/runner/work/SQLib/SQLib/build/libs/sqlib-all.jar`.
2) You then upload this file as an artifact, which is named `sqlib-2.1.4`.
3) In the next job, you download the same artifact to `/home/runner/work/SQLib/SQLib/`. This results in the creation of the file `/home/runner/work/SQLib/SQLib/sqlib-2.1.4`.
4) You then instruct `mc-publish` to upload `/home/runner/work/SQLib/SQLib/sqlib-2.1.4.jar` (note the file extension!).
5) Finally, you delete the artifact.

You can rectify the configuration by ensuring your artifact has the `.jar` extension. However, I recommend going a step further to simplify your entire build process. Here are my suggestions:

1. There's no need for a separate job to publish files with `mc-publish`.
2. Your current process appears to upload and download artifacts merely to rename the Gradle output, which seems excessive.
   1. You can use the shell command `mv "${{ github.workspace }}/build/libs/sqlib-all.jar" "${{ github.workspace }}/sqlib-${{ github.ref_name }}.jar"` or `cp "${{ github.workspace }}/build/libs/sqlib-all.jar" "${{ github.workspace }}/sqlib-${{ github.ref_name }}.jar"` to achieve the same renaming effect.
   2. Better still, you could modify your `build.gradle` so that the output file already has the desired name. For example, the Sodium project uses a great [approach](https://github.com/CaffeineMC/sodium-fabric/blob/2cd4aaa12eb619d2fc66e91c62f6f6ed58b57e84/build.gradle#L76-L98) that I've personally adapted for [my own mods](https://github.com/Kir-Antipov/packed-inventory/blob/8b857fc741cf6bc8490e1c12f6e59e9770c54018/build.gradle#L79-L108).

I hope this helps. Please let me know if you require further assistance!

**Comment by MrNavaStar** [comment]
Thank you for your response! This was my first time using Github action in a project so I agree that my setup is not ideal. It all seems to be working now! I will certainly look into that gradle approach as it seems much more elegant, but the rename command is a simple fix for now.

Thanks again!

**Comment by Kir-Antipov** [comment]
You are welcome! :)
