### ISSUE TITLE
Modrinth URL is incorrect

### ISSUE THREAD

**Issue by Hugman76** [Kir-Antipov/mc-publish#73]
For version 3.3. I uploaded one of my mods and the url had the mod name with the version slug.

Here is the action: https://github.com/DawnTeamMC/Promenade/actions/runs/5356261383
And its workflow: https://github.com/DawnTeamMC/Promenade/actions/runs/5356261383/workflow

The generated Modrinth URL is `https://modrinth.com/mod/promenade/version/Promenade v4.0.0` instead of `https://modrinth.com/mod/promenade/version/v4.0.0`

**Comment by Kir-Antipov** [comment]
This is the line to blame:

https://github.com/Kir-Antipov/mc-publish/blob/69d94c54c333ce6df545827ddfdd3ecb7f1ac8b8/src/platforms/modrinth/modrinth-uploader.ts#L66

I erroneously used `version.name` instead of `version.version_number`, likely due to fatigue from the approaching deadline. Thank you for bringing this to my attention!

Are other URLs ok?

**Comment by Kir-Antipov** [comment]
Congrats on 15 millions downloads by the way! :)

**Comment by Hugman76** [comment]
Other URLs (CurseForge/GitHub) are fine! And thanks a lot for the comment :D
