### ISSUE TITLE
[help] Error while parsing JSON: missing field `version_number` 

### ISSUE THREAD

**Issue by Fauli1221** [Kir-Antipov/mc-publish#78]
Publishing on modrinth won't work, and it gives me this error

![grafik](https://github.com/Kir-Antipov/mc-publish/assets/43648117/f7feb663-e72c-4ae0-97c1-06976e46012e)

[Pipeline](https://github.com/Fauli1221/PonyCraftANewGenerationVanilla/actions/runs/5519498475/jobs/10064834990)

[workflow](https://github.com/Fauli1221/PonyCraftANewGenerationVanilla/blob/main/.github/workflows/build.yaml#L130)

**Comment by Kir-Antipov** [comment]
So, here's what's happening:

```ts
options.version ||= githubContext.payload.release?.tag_name || metadata?.version;
```

At the moment, `mc-publish` is incapable of inferring the version of your modpack as it doesn't yet support reading `.mrpack` files *(this feature, however, is slated for inclusion in the upcoming v4.0 release)*. Additionally, because the action was triggered by a tag creation, there isn't a release available from which to infer the version.

Specifically in your case, I'd categorize it as a bug, because `mc-publish` could use `GITHUB_REF` in this scenario to determine the modpack version (i.e., `v1.0.9`). I'll address this problem shortly.
