### ISSUE TITLE
Github token from incorrect Client ID

### ISSUE THREAD

**Issue by 0ql** [Kir-Antipov/mc-publish#83]
```
Error: Error: Failed to upload file: 401 (Unauthorized, {"error":"unauthorized","description":"Authentication Error: GitHub Token from incorrect Client ID"})
```

https://github.com/0ql/kaffees_dual_ride/actions/runs/5524309305/jobs/10160137707

Anybody know what this means? The very same configuration worked just fine a few months ago.

**Comment by Kir-Antipov** [comment]
Please, check #49. In short, Modrinth tokens are not perpetual and have an expiration timeline, so they cease to be functional after a certain point in time *(that's why your configuration worked fine before and does not now)*. Therefore, it is critical to renew them at regular intervals to maintain uninterrupted services.

**Comment by 0ql** [comment]
Thank you for the swift response. I actually checked out the issue but given that the Error was different didn't think much of it.

**Comment by Kir-Antipov** [comment]
That issue is pretty old and Modrinth developers are pretty active folks, so the whole `auth` module has been re-written since then. Thus, the error message may have changed too :)
