### ISSUE TITLE
Modrinth Featured Support

### ISSUE THREAD

**Issue by fxmorin** [Kir-Antipov/mc-publish#9]
So there are a couple of things to do with modrinth's featured tag for uploads that I would like.
1) Having the action automatically remove `featured` from the last upload that matches the same mc versions.
2) Being able to toggle if the upload should be featured. (and maybe toggle it based on the release type)

**Comment by Kir-Antipov** [comment]
As for your second point, it's as easy as adding new action input `modrinth-featured` that accepts boolean values.

> and maybe toggle it based on the release type

There's no need to make this an in-built feature, because it's possible for user to achieve the same effect by passing a dynamically computed value into the new input.

------

As for the first one, it's a little bit unclear for me, how this will be applied in practice. Imagine, you've just uploaded a new version, that supports mc versions from 1.18 to 1.18.2, while previous one supported only 1.18. Should it be delisted?

**Comment by fxmorin** [comment]
Yes the featured part is pretty easy.

> As for the first one, it's a little bit unclear for me, how this will be applied in practice. Imagine, you've just uploaded a new version, that supports mc versions from 1.18 to 1.18.2, while previous one supported only 1.18. Should it be delisted?

I guess it should, basically if it replaces the version it should.
