### ISSUE TITLE
[Help Needed] TypeError: Cannot Read 'includes' Property

### ISSUE THREAD

**Issue by Tomate0613** [Kir-Antipov/mc-publish#91]
I am encountering an issue while attempting to set up 'mc-publish,' and I could use some assistance in resolving it. Here is the specific error message I'm encountering:

- [Error Details](https://github.com/Tomate0613/total-dragon/actions/runs/6275297561/job/17043210215#step:8:129)

The error message I'm receiving reads as follows:
```
TypeError: Cannot read properties of undefined (reading 'includes')
```

I suspect that I may have made a mistake in my configuration or usage, but the error message itself doesn't provide much guidance. If this issue is due to my configuration, it would be helpful to receive a more informative error message that could pinpoint the problem. Any help or insights into what might be causing this issue would be greatly appreciated.

**Comment by Kir-Antipov** [comment]
> I suspect that I may have made a mistake in my configuration or usage

Even if you did, the code should not crash due to an unhandled NRE. As you've mentioned, the error message is extremely unhelpful. Even I don't know where this came from, so this definitely shouldn't have happened.

I've downloaded the artifacts from the faulted workflow you provided and will try to debug the issue. I'll get back to you as soon as I identify the problem!

**Comment by Kir-Antipov** [comment]
Oh, wow. That's definitely on me. Turns out, all this time, `mc-publish` has been unable to handle version ranges with wildcards (like `1.20.*` that you are using here). At the moment, you can use `1.20.x` instead. I apologize for the inconvenience.

**Comment by Kir-Antipov** [comment]
P.S. - #72. You do not need both `fabric` and `fabric-api`, they are the same thing.
